# Generated by Django 5.1.2 on 2024-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=2000)),
                ('bankId', models.CharField(max_length=2000)),
                ('accessToken', models.CharField(max_length=2000)),
                ('fundingSourceUrl', models.CharField(max_length=2000)),
                ('shareableId', models.CharField(max_length=2000)),
            ],
        ),
    ]
